### ISSUE TITLE
6.2 Creación CSS

### ISSUE THREAD

**Issue by MichaelBordaPoli** [ISWPOLI/MMLI#35]
**Descripción**

Diseñar pagina web de acuerdo a los mockups aprobados.
- [x] Pagina de inicio
- [x] Pagina de log in
- [x] Pagina de registro usuarios
- [x] Pagina de mi cuenta
- [x] Pagina de home aplicación
- [x] Pagina de reporte de horas 
- [x] Pagina de registro de proyectos
- [x] Pagina de registro de cliente
- [x] Pagina de reportes

**Comment by Marynela** [comment]
[mmli.zip](https://github.com/ISWPOLI/MMLI/files/1283067/mmli.zip)

**Comment by Marynela** [comment]
Se terminan las paginas de acuerdo a los mockups planteados.
