### ISSUE TITLE
0.2 Herramientas Para Ejecución Del Proyecto

### ISSUE THREAD

**Issue by Marynela** [ISWPOLI/MMLI#41]
*Descripción*

Definir las herramientas que se utilizaran para la ejecución del proyecto.

- [x] Gestor Base de datos: SQL Server 
- [x] Diseño de mockups: Balsamiq
- [x] IDE de programación: Visual Studio como IDE de programación, en lenguaje C#, HTML, CSS, Javascript

**Comment by MichaelBordaPoli** [comment]
Se definieron las herramientas a utilizar en el proyecto.
